Polytoria/Docs

- docs/classes/DynamicInstance/Properties/LocalPosition.md
- docs/classes/DynamicInstance/Properties/LocalRotation.md
- docs/classes/Instance/Static functions/New.md
- docs/classes/Lighting/Properties/SunColor.md
- docs/classes/NPC/Properties/HeadColor.md
- docs/classes/NPC/Properties/Health.md
- docs/classes/NPC/Properties/LeftArmColor.md
- docs/classes/NPC/Properties/LeftLegColor.md
- docs/classes/NPC/Properties/MaxHealth.md
- docs/classes/NPC/Properties/MoveTarget.md
- docs/classes/NPC/Properties/RightArmColor.md
- docs/classes/NPC/Properties/RightLegColor.md
- docs/classes/NPC/Properties/TorsoColor.md
- docs/classes/NPC/index.md
- docs/classes/Player/index.md
- docs/classes/Players/index.md
- docs/classes/PointLight/Properties/Color.md
- docs/enums/SkyboxPreset.md
- docs/static-classes/TweenService/index.md
[fix] Position/Rotation typo
[add] Add NPC
[update] More info about tweening in TweenService
> Add n Fix stuff!

- docs/static-classes/Camera/Properties/IsFirstPerson.md
- docs/static-classes/Camera/Properties/Rotation.md
- docs/static-classes/Tween/Functions/TweenVector3.md
Just went to fix a couple Camera properties that said the wrong thing 👍
> Fixing few Camera Properties

- docs/classes/Tool/Functions/Play.md
Animations list so that people know what animations are offered
> Added animations list

- docs/classes/RemoteEvent/Functions/Invoke.md
> Add Removed Banner to Remote Events

- docs/classes/UIButton/Events/Clicked.md
add returns void
add example code
> Update :Clicked (UIButton)

- docs/classes/PlayerDefaults/Functions/LoadDefaults.md
> Add :LoadDefaults

- docs/index.md
Additions:
- Download links
- Discord links
- About Polytoria
Removed:
- Some phrases.
> index.md remake

- docs/classes/BaseScript/index.md
- docs/classes/Climbable/index.md
- docs/classes/Environment/index.md
- docs/classes/Game/index.md
- docs/classes/Hidden/index.md
- docs/classes/Instance/index.md
- docs/classes/Lighting/index.md
- docs/classes/Player/index.md
- docs/classes/Players/index.md
- docs/classes/ScriptService/index.md
@BrixsterPlanet @BrixsterPlanet @BrixsterPlanet @BrixsterPlanet @BrixsterPlanet @BrixsterPlanet @BrixsterPlanet @BrixsterPlanet @BrixsterPlanet @BrixsterPlanet @BrixsterPlanet @BrixsterPlanet @BrixsterPlanet
> change Instance.new to Instance.New

- docs/classes/Tool/Events/Deactivated.md
> Updated Deactivated.md

- docs/classes/Spotlight/index.md
> Fix Spotlight description

- docs/user-guide/basic/index.md
Removed old and EOL versions:
- Ubuntu 18.04 & 20.04 EOL -> Ubuntu 22.04 LTS
- I changed CentOS for Fedora because it is not used anymore as a desktop system.
- Added Debian 12, as it is the most recent version;
==== Hardware Changes ===========
- I changed 1gb of RAM to 2gb of RAM because there are almost none laptops with less than 2gb in the market, because he can't handle most of the mainstream apps.
> Update client specs

- docs/classes/Environment/Properties/PartDestroyHeight.md
- docs/classes/Player/Functions/Kick.md
- docs/classes/Tool/Events/Deactivated.md
Added the code example for `Environment.PartDestroyHeight` and documented `Player:Kick()` `reason` parameter.
> Update example code

- docs/directory.md
- docs/objects/static-classes/Input.md
- docs/theme/main.html
code had "poly-newdocs" referenced so the icons wouldn't appear on the meta embeds
> remove the rest of the poly-newdocs references

- mkdocs.yml
> Put the dash outside of the link in the footer

- docs/objects/effects/Sound.md
- docs/objects/world/Text3D.md
I documented the Text3D class `.Font` property and the Sound class `.MaxDistance` property.
Also:
- Not sure what the `.Damage` parameter order is in the `:CreateExplosion` method on the Environment service/class
- The `.Size` property of the Player class does not need to be documented due to the Player class inheriting the DynamicInstance class which has a `.Size` property
@StarManTheGamer sent a list of the undocumented stuff Willem found. I just did the easy documentation stuff and will leave the annoying stuff to them lol
> Document .Font and .MaxDistance Properties

- CONTRIBUTING.md
- docs/objects/effects/PointLight.md
- docs/objects/effects/SpotLight.md
- docs/objects/static-classes/Achievements.md
- docs/tutorials/basic-scripting/accessing-objects.md
- docs/tutorials/getting-started/creator-setup.md
Fixes misspellings on the docs (they are even on CONTRIBUTING.md)
> Fix misspellings on docs

- docs/objects/game/Game.md
- main.py
Various minor grammar fixes (sorry, not trying to nitpick 🙃)
> Various grammar fixes to Game.md and main.py

- README.md
- docs/objects/game/Game.md
- docs/objects/game/Lighting.md
- docs/objects/game/Players.md
- docs/objects/scripting/BaseScript.md
- docs/objects/scripting/ModuleScript.md
- docs/objects/scripting/NetworkEvent.md
- docs/objects/static-classes/Achievements.md
- docs/objects/static-classes/Camera.md
- docs/objects/static-classes/CoreUI.md
- docs/objects/system/Instance.md
- Added `deltaTime` parameter to game:Rendered event
- Updated some wording of properties to use "Determines"
- Added readonly macro to `Players.LocalPlayer` property
- Updated `BaseScript` note wording and changed class links to use classLink macro
- Added "current issues" to the "BETA Feature" note at the top of the `ModuleScript` class documentation
- Reordered `NetworkEvent` Methods and added 1 singular "s" to the class description
- Added `Achievements` static class rate-limit information (info from Brixster)
- Updated `README.md`
> Improvements

- docs/objects/static-classes/Http.md
> add headers to delete and put

- docs/index.html
it wasnt centered properly before cause index uses a silly screen size and didnt notice
Thanks for taking the time to contribute to the Polytoria documentation project!
Please ensure that this PR meets the following criteria before submitting (you may delete this section after reading):
> Phicks centering of showcased games

- .github/workflows/prettier.yml
- docs/objects/effects/ImageSky.md
Creates a pull request with the changes
Thanks for taking the time to contribute to the Polytoria documentation project!
Please ensure that this PR meets the following criteria before submitting (you may delete this section after reading):
> create pull request with changes

- .github/workflows/prettier.yml
- docs/objects/effects/ImageSky.md
prettier will UPLOAD CHANGES TO A PULL REQUEST
Thanks for taking the time to contribute to the Polytoria documentation project!
Please ensure that this PR meets the following criteria before submitting (you may delete this section after reading):
> OK I SWEAR ITLL WORK NOW

- docs/objects/game/Player.md
Fixes #90 
The whole method and event parameter system needs a rewrite, but maybe for another day. @BrixsterPlanet you said you wanted to 🤷 
(unreadable mess)
^ I would assume Willem knows his own game's scripting API
> Add .Chatted event "Event" parameter

- docs/objects/game/Player.md
- main.py
[.ShirtID, .PantsID, and .FaceID Player class properties](https://github.com/Polytoria/Docs/commit/063f1cd3d2a8a3a2d74d8c9423e613a695c3539f)
> .ShirtID, .PantsID, and .FaceID Player class properties

- docs/contributors.html
- docs/style.css
this commit adds the latest commits to the contributors page (pretty swag if i say so myself)
> add commits to contributors page

- docs/contributors.html
> fix escaping html 💀💀💀

- docs/index.html
- mkdocs.yml
Fixed broken CDN links on the main page, fixed a username typo, and updated the copyright year for 2025.
> Fixed broken CDN links, username typo, and updated the copyright year

- docs/tutorials/getting-started/creator-setup.md
- docs/tutorials/getting-started/index.md
Basically fixed some unneededly long and hard to read sentences on the "Getting Started" page and neatened IDEs list. Fixed some other typos too
Thanks for taking the time to contribute to the Polytoria documentation project!
Please ensure that this PR meets the following criteria before submitting (you may delete this section after reading):
> Fixed typos and neatened things up (inner English major go brr)
